package pageUIs;

public class AbstractPageUI { 
	
	public static final String HEADER_HOME_LOGO_LINK = "//div[@class='header-logo']";
	public static final String HEADER_WISHLIST_LINK = "//a[@class='ico-wishlist']";
	public static final String FOOTER_WISHLIST_LINK = "//a[text()='Wishlist']";
	public static final String HEADER_SHOPPING_CART_LINK = "//li[@id='topcartlink']";
	public static final String FOOTER_SHOPPING_CART_LINK = "//a[text()='Shopping cart']";
	public static final String HEADER_REGISTER_LINK = "//a[@class='ico-register']";
	public static final String HEADER_LOGIN_LINK = "//a[@class='ico-login']";
	public static final String HEADER_MYACCOUNT_LINK = "//a[@class='ico-account']";
	public static final String HEADER_LOGOUT_LINK = "//a[@class='ico-logout']";
	public static final String FOOTER_SITEMAP_LINK = "//a[text()='Sitemap']";
	public static final String FOOTER_SHIPPING_AND_RETURNS_LINK = "//a[text()='Shipping & returns']";
	public static final String FOOTER_SEARCH_LINK = "//a[text()='Search']";
	public static final String FOOTER_NEWS_LINK = "//a[text()='News']";
	public static final String FOOTER_MYACCOUNT_LINK = "//a[text()='My account']";
	public static final String FOOTER_ORDERS_LINK = "//a[text()='Orders']";
	public static final String FOOTER_FACEBOOK_LINK = "//a[text()='Facebook']";
	public static final String FOOTER_TWITTER_LINK = "//a[text()='Twitter']";
	public static final String DYNAMIC_HEADER_LINK_1 = "//div[@class='header-links']//a[text()='%s']";
	public static final String DYNAMIC_HEADER_LINK_2 = "//div[@class='header-links']//a/span[text()='%s']";
	public static final String DYNAMIC_HEADER_MENU = "//ul[@class='top-menu notmobile']//a[contains(text(),'%s')]";
	public static final String DYNAMIC_FOOTER_LINK = "//div[@class='footer']//a[text()='%s']";
	public static final String DYNAMIC_LINK = "//div[@class='%s']//a[text()='%s']";
	public static final String DYNAMIC_TEXTBOX = "//input[@id='%s']";
	public static final String DYNAMIC_TEXTAREA = "//textarea[@id='%s']";
	public static final String DYNAMIC_TEXTBOX_TEXTAREA = "(//input | //textarea)[@id='%s']";
	public static final String DYNAMIC_CHECKBOX = "//input[@id='%s']";
	public static final String DYNAMIC_BUTTON = "(//input | //button)[@value='%s']";
	public static final String PRODUCT_OVERVIEW_ACTION_BUTTON = "//div[@class='overview']//input[@value='%s']";
	public static final String DYNAMIC_RADIOBUTTON = "//input[@id='%s']";
	public static final String DYNAMIC_DROPDOWN_LIST_BY_NAME = "//select[@name='%s']";
	public static final String DYNAMIC_DROPDOWN_LIST_BY_ID = "//select[@id='%s']";
	public static final String DYNAMIC_DROPDOWN_ITEM_SELECTED_BY_NAME = "//select[@name='%s']/option[@selected='' and text()='%s']";
	public static final String DYNAMIC_DROPDOWN_ITEM_SELECTED_BY_ID = "//select[@id='%s']/option[@selected='selected' and text()='%s']";
	public static final String DYNAMIC_REQUIRED_FIELD_ERROR_MGS = "//span[@id='%s-error' and text()='%s']";
	public static final String DYNAMIC_REQUIRED_FIELD_ERROR_MGS_TEXT = "//span[@id='%s-error']";
	public static final String DYNAMIC_REQUIRED_FIELD_ERROR_ICON = "//input[@id='%s']/following-sibling::span[@class='required' and text()='*']";
	public static final String DYNAMIC_PAGE_FORM = "//div[@class='%s']";
	public static final String PAGE_TITLE_TEXT = "//div[@class='page-title']/h1";
	public static final String DYNAMIC_ADDTOCART_BUTTON = "//h2[@class='product-title']/a[text()='%s']/parent::h2/following-sibling::div[@class='add-info']//input[@value='Add to cart']";
	public static final String RESULT_MESSAGE_TEXT = "//div[@class='result']";
	public static final String DYNAMIC_PRODUCT_BY_NAME = "//h2[@class='product-title']/a[text()='%s']";
	public static final String ALL_PRODUCT_TITLE_DISPLAYED_ON_PAGE = "//h2[@class='product-title']/a";
	public static final String DYNAMIC_PRODUCT_ACTION_BY_NAME = "//a[contains(text(),'%s')]/parent::h2[@class='product-title']/following-sibling::div//input[@value='%s']";
	public static final String ACTION_SUCCESS_MSG = "//div[@class='bar-notification success']/p[@class='content']";
	public static final String NOTIFICATION_BAR_CLOSE_BUTTON = "//div[@class='bar-notification success']/span[@class='close']";
	public static final String TABLE_COLUMN_PRODUCT_NAME_ALL = "//tbody/tr/td[@class='product']";
	public static final String DYNAMIC_TABLE_PRODUCT_NAME = "//a[@class='product-name' and contains(text(),'%s')]";
	public static final String PAGE_BODY_NO_DATA_TEXT = "//div[@class='no-data']";
	public static final String WISHLIST_SHOPPING_CART_PAGE_BODY_MSG_DISPLAYED = "//div[@class='no-data' and text()='%s']";
	public static final String DYNAMIC_TABLE_COLUMN_BY_CLASS_VALUE_ALL = "//tbody/tr/td[@class='%s']/input";
	public static final String DYNAMIC_TABLE_PRODUCT_NAME_ONE_BY_NAME = "//td[@class='product']//a[contains(text(),'%s')]";
	public static final String DYNAMIC_PRODUCT_QUANTITY_TEXTBOX_BY_NAME = "//td[@class='product']//a[contains(text(),'%s')]/ancestor::tr/td[@class='quantity']/input";
	public static final String DYNAMIC_PRODUCT_TOTAL_PRICE_BY_NAME = "//td[@class='product']//a[contains(text(),'%s')]/ancestor::tr/td[@class='subtotal']";
	public static final String DYNAMIC_TABLE_COLUMN_BY_NAME = "//td[@class='product']//a[contains(text(),'%s')]/ancestor::tr/td[@class='%s']";
	public static final String DYNAMIC_TABLE_COLUMN_TEXT_BY_NAME = "//td[@class='product']//a[contains(text(),'%s')]/ancestor::tr/td[@class='%s']/span";
	public static final String UPDATE_BUTTON = "//input[@value='Update wishlist' or @value='Update shopping cart']";
	public static final String HEADER_TOP_CART_LINK = "//li[@id='topcartlink']";
	public static final String FLYOUT_TOP_CART_DISPLAYED = "//div[@id='flyout-cart']";
	public static final String HEADER_MINI_SHOPPING_CART_QUANTITY_TEXT = "//span[@class='cart-qty']";
	public static final String HEADER_MINI_SHOPPING_CART_PRODUCT_ATTRIBUTE = "//div[@class='mini-shopping-cart']//div[@class='product']";
	public static final String HEADER_MINI_SHOPPING_CART_PRODUCT_NAME_ALL = "//div[@class='mini-shopping-cart']//div[@class='product']/div[@class='name']/a";
	public static final String DYNAMIC_HEADER_MINI_SHOPPING_CART_LABEL = "//div[@class='mini-shopping-cart']/div[@class='%s']";
	public static final String PRODUCT_ATTRIBUTE_EDIT_LINK = "//div[@class='edit-item']//a[contains(text(),'Edit')]";
	public static final String PRODUCT_DETAIL_PRICE = "//div[@class='product-price']/span";
	public static final String PRODUCT_OVERVIEW_PRICE = "//div[@class='prices']/span";
	public static final String PRODUCT_ATTRIBUTE_ALL_TEXT = "//div[@id='flyout-cart']//div[@class='attributes']";
	public static final String DYNAMIC_RADIO_BUTTON_CHECKBOX_BY_LABEL = "//label[contains(text(),'%s')]/preceding-sibling::input";
	
}